### ISSUE TITLE
ImportError of 'crocoddyl_ros' in python program due to incomplete library linking with boost.

### ISSUE THREAD

**Issue by tkpf** [RobotMotorIntelligence/crocoddyl_msgs#19]
After building the ros package and sourcing the setup.bash, I tried to import the 'crocoddyl_ros' package into my python program (e.g. python -c "import crocoddyl; import crocoddyl_ros") . It failed with the error: 

ImportError: xxx/catkin_ws/devel/lib/python3/dist-packages/crocoddyl_ros.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN5boost6python9converter25rvalue_from_python_stage2EP7_objectRNS1_30rvalue_from_python_stage1_dataERKNS1_12registrationE

I figured it is a linking problem with cmake and spottet that in the 'CMakeLists.txt' the variables 'Boost_INCLUDE_DIRS', 'Boost_LIBRARIES' do not get initialized.

Adding 
'find_package(Boost REQUIRED COMPONENTS python38)'
at the top of 'CMakeLists.txt' and rebuilding fixed it for me.

**Comment by cmastalli** [comment]
This is weird as we've jobs for ROS1 and ROS2 where we test this. @Sergim96 -- can you check this?

**Comment by Sergim96** [comment]
Hi @tkpf I tested this on an Ubuntu 20.04 with ROS Noetic, and I'm not able to replicate this error. 

Could you give us more details of your system or provide a Dockerfile with the error so we can inspect it?

**Comment by tkpf** [comment]
Hi together,
Thanks for the fast response. 
First of all some information on my system setup: I am on a Ubuntu 22.04 as a VM using Oracle VirtualBox. My host system is a Windows 11 os, which should not make any difference though.

As my preceeding system setup was very dirty, I decided to setup a clean Ubuntu 20.04 VM to try to reproduce the error. I attached the bash history dump to this message (one shortened, the other one of original length also containing duplicated commands or failing commands e.g. due to spelling mistakes). As you can see, from a clean VM Ubuntu 20.04 system, I only installed all the dependencies and then tried to build the crocoddyl_msgs package- nothing more. Unfortunately, still failing.

The error still stayed and was solved through the provided hack above. So also on a clean (VM) system I could replicate the error.

I want to highlight again, that building succeeds but it seems to be a linkage issue when importing into python. Also in the given CMakeLists.txt file line 68/69 we try to link to the boost library, but never try to locate the boost package via 'find_package' before as we are doing with eigen3 and pinocchio. So for me the error seems reasonable. Please correct me if I am wrong and setting variables ${Boost_LIBRARIES} ${Boost_Python_LIBRARY} should normally be done implicitly.

Thanks for your help in advance!
If you need more specific files please reach out again.

[issue_boost_linkage_crocoddyl_msgs.txt](https://github.com/us
[full_length.txt](https://github.com/user-attachments/files/17910325/full_length.txt)
er-attachments/files/17910221/issue_boost_linkage_crocoddyl_msgs.txt)

**Comment by tkpf** [comment]
[full_length.txt](https://github.com/user-attachments/files/17910394/full_length.txt)
[issue_boost_linkage_crocoddyl_msgs.txt](https://github.com/user-attachments/files/17910395/issue_boost_linkage_crocoddyl_msgs.txt)

**Comment by Sergim96** [comment]
Hi @tkpf I'm closing this issue as I can't replicate it
